spring:
  application:
    name: two-datasources
  postgres-datasource:
    xa-properties:
      url: jdbc:postgresql://localhost:5432/twodatasources
      user: twodatasources
      password: twodatasources
    xa-data-source-class-name: org.postgresql.xa.PGXADataSource
    unique-resource-name: 'postgres'
  mysql-datasource:
    xa-properties:
      url: jdbc:mysql://localhost:3306/twodatasources
      user: root
      password: root
    xa-data-source-class-name: com.mysql.cj.jdbc.MysqlXADataSource
    unique-resource-name: 'mysql'
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  jta:
    enabled: true
    service: com.atomikos.icatch.standalone.UserTransactionServiceFactory
    max-actives: 200
    enable-logging: true
server:
  port: 1980
